name: CI

on: 
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Test simple lib
        run: |
          cd ./examples/simple_lib && mkdir build && cd build
          cmake .. && cmake --build . && cd ..

      - name: Test lib and bin
        run: |
          cd ./examples/lib_and_bin && mkdir build && cd build
          cmake .. && cmake --build . && cd ..

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test simple lib
        run: |
          cd ./examples/simple_lib && mkdir build && cd build
          cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && cmake --build . && cd ..

      - name: Test lib and bin
        run: |
          cd ./examples/lib_and_bin && mkdir build && cd build
          cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. && cmake --build . && cd ..