name: CI

on: 
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [clang]
        os: [ubuntu-latest, windows-latest]
        
    steps:
      - uses: actions/checkout@v2

        env:
          C: clang 
          CXX: clang++

      - name: Test simple lib
        run: |
          cd ./examples/simple_lib && mkdir build && cd build
          cmake -G Ninja .. && cmake --build . && cd ..

      - name: Test lib and bin
        run: |
          cd ./examples/lib_and_bin && mkdir build && cd build
          cmake -G Ninja .. && cmake --build . && cd ..
