name: CI

on: 
  push:
    paths-ignore:
      - 'README.md'

jobs:
  examples-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Test simple lib
        run: |
          cd ./examples/simple_lib && mkdir build && cd build
          cmake .. && cmake --build . && cd ..

      - name: Test lib and bin
        run: |
          cd ./examples/lib_and_bin && mkdir build && cd build
          cmake .. && cmake --build . && cd ..

  examples-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test simple lib
        run: |
          cd ./examples/simple_lib && mkdir build && cd build
          cmake -Dgtest_force_shared_crt=ON .. && cmake --build . && cd ..

      - name: Test lib and bin
        run: |
          cd ./examples/lib_and_bin && mkdir build && cd build
          cmake -Dgtest_force_shared_crt=ON .. && cmake --build . && cd ..

  cmake-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: toml-parser test
        run: |
          cmake -P ./tests/toml/test_toml1.cmake