name: bastard-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test simple lib
        run: |
          cd ./examples/simple_lib && mkdir build && cd build
          cmake .. -DCMAKE_TESTING_ENABLED=True && cmake --build . && cd ..
      - name: Test lib and bin
        run: |
          cd ./examples/lib_and_bin && mkdir build && cd build
          cmake .. -DCMAKE_TESTING_ENABLED=True && cmake --build . && cd ..
